### ISSUE TITLE
Conflict with CleanWebpackPlugin

### ISSUE THREAD

**Issue by my-lalex** [pinojs/pino-webpack-plugin#58]
It seems that CleanWebpackPlugin is removing files generated by this plugin...

I'm currently investigating a bit to find out if the plugin is emitting files too soon, or CleanWebpackPlugin is removing files too late... I don't have much time to spend on this, so it could take a bit of time for me to find out.

If anyone already knows the plugin quite well and the answer, please let me know ;-)

**Comment by mcollina** [comment]
Unfortunately no :(.

**Comment by my-lalex** [comment]
It seems like CleanWebpackPlugin is using the compiler `done` hook, and the assets from its `stats` parameter.

By adding a log in the hook, I see that only the 'main.js' file is in the assets, none of the "pino files" are part of it...
I don't know how to add child compilers assets to the main one, still investigating...

**Comment by my-lalex** [comment]
I found a ggod article about childCompiler: https://medium.com/@prateekbh/my-experience-writing-a-webpacks-child-compiler-plugin-a1237c175947

> Step 5: Tell parent compiler about errors, assets and named chunks
>
> So even if you don’t do this it might work fine with you as the files are generated and you are free to use them. However if any other plugin(say HtmlWebpackPlugin) is trying to know the output, your additional assets will not be visible to it. In a nutshell you have to tell the parent compiler about the assets and named chunks you generated
>
> compilation.assets = Object.assign(childCompilation.assets,              compilation.assets);
> Please use the additionalAssets hook of the parent compilation to make sure you dont end up in a race condition with other plugin.

I'm still a bit confused about where to put the additionalAssets hook, but seem to be the good direction 😅

**Comment by my-lalex** [comment]
OK. I got the solution running, but I never made a PR 😅
I'm currently learning how to and send it

**Comment by simoneb** [comment]
Check this out https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by lalexdotcom** [comment]
Made it (this is my personal account) 😎 #59 

(my first PR, I'm so proud)
